services:
  server:
    build: .
    ports:
      - "3000:3000/tcp"
      - "3001:3001/udp"
    depends_on:
      - database
      - nats
    environment:
      MONGO_URI: "mongodb://database:27017/stp-23"
      NATS_URL: "nats://nats:4222"
  nats:
    image: nats:2
    ports:
      - "4222:4222"
  database:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
volumes:
  data:
