services:
  server:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - database
      - nats
  nats:
    image: nats:2
    ports:
      - "4222:4222"
  database:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
volumes:
  data:
