name: CI/CD

on:
  - push

jobs:
  deployment:
    name: Deployment Setup
    runs-on: ubuntu-latest
    steps:
      - name: Set Deployment Options
        id: deployment
        run: |
          case "$GITHUB_REF" in
            refs/tags/v*)
              VERSION="${GITHUB_REF:11}"
              PREFIX="${GITHUB_REF:11:1}"
          ;;
          esac
          echo "::set-output name=version::$VERSION"
          echo "::set-output name=prefix::$PREFIX"
    outputs:
      version: ${{ steps.deployment.outputs.version }}
      prefix: ${{ steps.deployment.outputs.prefix }}

  backend:
    name: Backend
    runs-on: ubuntu-latest
    needs: [ deployment ]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build the Docker Image
        if: needs.deployment.outputs.version
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          image_name: stp/settlers
          image_tag: ${{ needs.deployment.outputs.prefix }},${{ needs.deployment.outputs.version }}
      - name: Rancher Deploy
        if: needs.deployment.outputs.version
        uses: sekassel-research/actions-rancher-update@2.0.2
        with:
          rancher_url: ${{ secrets.RANCHER_URL }}
          rancher_token: ${{ secrets.RANCHER_TOKEN }}
          cluster_id: ${{ secrets.CLUSTER_ID }}
          project_id: ${{ secrets.PROJECT_ID }}
          namespace: ${{ secrets.NAMESPACE }}
          deployment: ${{ secrets.DEPLOYMENT }}-v${{ needs.deployment.outputs.prefix }}
          docker_image: ${{ secrets.DOCKER_REGISTRY }}/stp/settlers:${{ needs.deployment.outputs.version }}
      - name: Discord Notification
        if: needs.deployment.outputs.version
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            Eine neue Serverversion ist verfügbar: `${{ needs.deployment.outputs.version }}`
            <https://pioneers.uniks.de/api/v${{ needs.deployment.outputs.prefix }}>
